version: '3.8'
services:
  web:
    build: .
    command: gunicorn social_media_api.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=False
      - DJANGO_ALLOWED_HOSTS=localhost,yourdomain.com
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: social_db
      POSTGRES_USER: social_user
      POSTGRES_PASSWORD: examplepassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
