# Generated by Django 5.2.6 on 2025-09-12 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0006_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_add_book', 'can_add_book'), ('can_change_book', 'can_change_book'), ('can_delete_book', 'can_delete_book')]},
        ),
    ]
