# Generated by Django 5.2.5 on 2025-09-07 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0005_alter_task_options_task_assignees_task_creator_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('Can_Add_Book', 'Can_Add_Book'), ('Can_Change_Book', 'Can_Change_Book'), ('Can_Delete_Book', 'Can_Delete_Book')]},
        ),
    ]
